# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://magaiarsa.github.io/
title: Marília P. Gaiarsa 
email: gaiarsa.mp@gmail.com
author: Marília P. Gaiarsa
description: "Marília P. Gaiarsa's Website"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/magaiarsa  
  - icon: envelope-o
    title: email
    url: mailto:gaiarsa.mp@gmail.com
#  - icon: linkedin
#    title: linkedin
#    url: https://www.linkedin.com/in/dcassol/
  - icon: file-pdf-o
    title: CV
    url: img/GaiarsaCv.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
  - icon: twitter
    title: twitter
    url: https://twitter.com/magaiarsa

